package environment

const (
	DB_CONNECTION = "DB_CONNECTION"
	DB_HOST       = "DB_HOST"
	DB_PORT       = "DB_PORT"
	DB_DATABASE   = "DB_DATABASE"
	DB_USERNAME   = "DB_USERNAME"
	DB_PASSWORD   = "DB_PASSWORD"

	MAIL_MAILER       = "MAIL_MAILER"
	MAIL_HOST         = "MAIL_HOST"
	MAIL_PORT         = "MAIL_PORT"
	MAIL_USERNAME     = "MAIL_USERNAME"
	MAIL_PASSWORD     = "MAIL_PASSWORD"
	MAIL_ENCRYPTION   = "MAIL_ENCRYPTION"
	MAIL_FROM_ADDRESS = "MAIL_FROM_ADDRESS"
	MAIL_FROM_NAME    = "MAIL_FROM_NAME"

	HOST    = "HOST"
	PORT    = "PORT"
	APP_KEY = "APP_KEY"
)
